db:
  host: "${POSTGRES_HOST}"
  port: "${POSTGRES_PORT}"
  name: "${POSTGRES_DATABASE}"
  user: "${POSTGRES_USER}"
  password: "${POSTGRES_PASSWORD}"
  sslmode: disable
s3:
  are_local_buckets: true
  minio:
    key: "admin"
    secret: "${MINIO_ROOT_PASSWORD}"
    endpoint: "minio:9000"
    bucket: "${MINIO_BUCKET}"
log-file: ""
http:
apps:
  public-albums:
  cast:
  accounts:
  family:
key:
  encryption: "yvmG/RnzKrbCb9L3mgsmoxXr9H7i2Z4qlbT0mL3ln4w="
  hash: "KXYiG07wC7GIgvCSdg+WmyWdXDAn6XKYJtp/wkEU7x573+byBRAYtpTP0wwvi8i/4l37uicX1dVTUzwH3sLZyw=="
jwt:
  secret: "i2DecQmfGreG6q1vBj5tCokhlN41gcfS2cjOs9Po-u8="
smtp:
  host:
  port:
  username:
  password:
  email:
transmail:
  key:
apple:
  shared-secret:
stripe:
  us:
    key:
    webhook-secret:
  in:
    key:
    webhook-secret:
  whitelisted-redirect-urls: []
  path:
    success: "?status=success&session_id={CHECKOUT_SESSION_ID}"
    cancel: "?status=fail&reason=canceled"
webauthn:
  rpid: localhost
  rporigins:
    - "http://localhost:3001"
discord:
  bot:
    cha-ching:
      token:
      channel:
    mona-lisa:
      token:
      channel:
zoho:
  client-id:
  client-secret:
  refresh-token:
  list-key:
  topic-ids:
listmonk:
  server-url:
  username:
  password:
  list-ids:
internal:
  silent: false
  health-check-url:
  admins: []
  admin:
  disable-registration: false
  hardcoded-ott:
    local-domain-suffix:
    local-domain-value:
replication:
  enabled: false
  worker-url:
  worker-count: 6
  tmp-storage: tmp/replication
jobs:
  cron:
    skip: false
  remove-unreported-objects:
    worker-count: 1
  clear-orphan-objects:
    enabled: false
    prefix: ""